use_lockfile = false

[project]
name = "cqtkit"
r_version = "4.4"

repositories = [
    { alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2025-05-09/"}
]

dependencies = [
    "devtools",
    {name = "cqtkit", path = ".", dependencies_only = true, install_suggestions = true},
    "covr",
    "pkgpub",
]

